name = "JustSayIt"
uuid = "d7252348-293e-4f11-8d42-c8418dda4315"
authors = ["Samuel Omlin"]
version = "0.1.1"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Conda = "1.7"
DefaultApplication = "1"
JSON = "0.21"
MacroTools = "0.5"
ProgressMeter = "1.7"
PyCall = "1.93"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
